#!/bin/bash

# Copyright (c) 2011 Francesco Marella <francesco.marella@gmail.com>. All rights reserved.
# Use of this source code is governed by GPL v3 license that can be
# found in the COPYING file.

WORKDIR="$HOME/pg2/core"

if [ ! -d "$HOME/pg2" ];
then
    cd $HOME
    svn co http://svn.promotux.it/svn/promogest2/trunk pg2 | zenity --progress --pulsate --text="Attendere scaricamento sorgenti in corso..." --no-cancel
fi

cd $WORKDIR
exec python "$WORKDIR/promogest.py" "$@"
